import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';

import { Dish, PageTemplate, Search } from '@components';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<PageTemplate>
				<h1>Find options in Delivery near you.</h1>
				<Search />
				<h2>
					Discover your new favorite Delivery.Thousands of options at one click.
				</h2>
				<Dish />
			</PageTemplate>
		</>
	);
};

export default Home;
